apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
- ./namespace.yaml

helmChartInflationGenerator:
- chartName: crossplane
  chartVersion: 1.6.2
  chartRepoUrl: https://charts.crossplane.io/stable
  releaseName: crossplane
